project:
  type: website

website:
  title: "Polina Revina"
  navbar:
    left: 
      - projects.qmd
      - cv.qmd
format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css

editor: visual

